; Generated by c86 (BYU-NASM) 5.1 (beta) from yakc.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
YKInitialize:
	; >>>>> Line:	16
	; >>>>> void YKInitialize(){ 
	jmp	L_yakc_1
L_yakc_2:
	; >>>>> Line:	17
	; >>>>> id_counter = 1; 
	mov	word [id_counter], 1
	; >>>>> Line:	18
	; >>>>> running = 0; 
	mov	word [running], 0
	; >>>>> Line:	19
	; >>>>> YKTickNum = 0; 
	mov	word [YKTickNum], 0
	; >>>>> Line:	20
	; >>>>> YKIdleCount = 0; 
	mov	word [YKIdleCount], 0
	; >>>>> Line:	21
	; >>>>> YKCtxSwCount = 0; 
	mov	word [YKCtxSwCount], 0
	; >>>>> Line:	22
	; >>>>> isrdepth = 0; 
	mov	word [isrdepth], 0
	; >>>>> Line:	23
	; >>>>> NumTasks = 0; 
	mov	word [NumTasks], 0
	; >>>>> Line:	24
	; >>>>> YKNewTask(Idle, (void *) &IdleStk[256], 2); 
	mov	al, 2
	push	ax
	mov	ax, (IdleStk+512)
	push	ax
	mov	ax, Idle
	push	ax
	call	YKNewTask
	add	sp, 6
	mov	sp, bp
	pop	bp
	ret
L_yakc_1:
	push	bp
	mov	bp, sp
	jmp	L_yakc_2
	ALIGN	2
Dummy:
	; >>>>> Line:	32
	; >>>>> void Dummy(){} 
	jmp	L_yakc_4
L_yakc_5:
	; >>>>> Line:	32
	; >>>>> void Dummy(){} 
	mov	sp, bp
	pop	bp
	ret
L_yakc_4:
	push	bp
	mov	bp, sp
	jmp	L_yakc_5
	ALIGN	2
YKNewTask:
	; >>>>> Line:	33
	; >>>>> void YKNewTask(void (* task)(void),void *taskStack, unsigned char priority){ 
	jmp	L_yakc_7
L_yakc_8:
	; >>>>> Line:	37
	; >>>>> newTCB->task = task; 
	mov	al, byte [bp+8]
	xor	ah, ah
	mov	cx, 42
	imul	cx
	add	ax, tasks
	mov	word [bp-6], ax
	; >>>>> Line:	37
	; >>>>> newTCB->task = task; 
	mov	si, word [bp-6]
	add	si, 40
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	38
	; >>>>> newTCB->id = id_counter++; 
	mov	ax, word [id_counter]
	inc	word [id_counter]
	mov	si, word [bp-6]
	mov	word [si], ax
	; >>>>> Line:	39
	; >>>>> newTCB->state = 1; 
	mov	si, word [bp-6]
	add	si, 32
	mov	word [si], 1
	; >>>>> Line:	40
	; >>>>> newTCB->first_time = 1; 
	mov	si, word [bp-6]
	add	si, 34
	mov	word [si], 1
	; >>>>> Line:	42
	; >>>>> newTCB->context.sp = (int 
	mov	si, word [bp-6]
	add	si, 12
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	43
	; >>>>> newTCB->context.bp = (int)taskStack; 
	mov	si, word [bp-6]
	add	si, 14
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	44
	; >>>>> newTCB->context.si = 0; 
	mov	si, word [bp-6]
	add	si, 16
	mov	word [si], 0
	; >>>>> Line:	45
	; >>>>> newTCB->context.di = 0; 
	mov	si, word [bp-6]
	add	si, 18
	mov	word [si], 0
	; >>>>> Line:	47
	; >>>>> newTCB->context.cs = 0; 
	mov	si, word [bp-6]
	add	si, 20
	mov	word [si], 0
	; >>>>> Line:	48
	; >>>>> newTCB->context.ds = 0; 
	mov	si, word [bp-6]
	add	si, 22
	mov	word [si], 0
	; >>>>> Line:	49
	; >>>>> newTCB->context.ss = 0; 
	mov	si, word [bp-6]
	add	si, 24
	mov	word [si], 0
	; >>>>> Line:	50
	; >>>>> newTCB->context.es = 0; 
	mov	si, word [bp-6]
	add	si, 26
	mov	word [si], 0
	; >>>>> Line:	52
	; >>>>> newTCB->tickNum = -1; 
	mov	si, word [bp-6]
	add	si, 36
	mov	word [si], -1
	; >>>>> Line:	53
	; >>>>> newTCB->context.tstamp = 0; 
	mov	si, word [bp-6]
	add	si, 30
	mov	word [si], 0
	; >>>>> Line:	54
	; >>>>> newTCB->priority = priority; 
	mov	si, word [bp-6]
	add	si, 38
	mov	al, byte [bp+8]
	mov	byte [si], al
	; >>>>> Line:	71
	; >>>>> tasks[priority] = *newTCB; 
	mov	al, byte [bp+8]
	xor	ah, ah
	mov	cx, 42
	imul	cx
	add	ax, tasks
	mov	word [bp-8], ax
	mov	di, word [bp-8]
	mov	si, word [bp-6]
	mov	cx, 21
	rep
	movsw
	; >>>>> Line:	72
	; >>>>> NumTasks++; 
	inc	word [NumTasks]
	; >>>>> Line:	73
	; >>>>> if (running) YKScheduler(); 
	mov	ax, word [running]
	test	ax, ax
	je	L_yakc_9
	; >>>>> Line:	73
	; >>>>> if (running) YKScheduler(); 
	call	YKScheduler
L_yakc_9:
	mov	sp, bp
	pop	bp
	ret
L_yakc_7:
	push	bp
	mov	bp, sp
	sub	sp, 8
	jmp	L_yakc_8
	ALIGN	2
YKRun:
	; >>>>> Line:	75
	; >>>>> void YKRun(){ 
	jmp	L_yakc_11
L_yakc_12:
	; >>>>> Line:	76
	; >>>>> running = 1; 
	mov	word [running], 1
	; >>>>> Line:	77
	; >>>>> while(1) 
	jmp	L_yakc_14
L_yakc_13:
	; >>>>> Line:	78
	; >>>>> YKScheduler(); 
	call	YKScheduler
L_yakc_14:
	jmp	L_yakc_13
L_yakc_15:
	mov	sp, bp
	pop	bp
	ret
L_yakc_11:
	push	bp
	mov	bp, sp
	jmp	L_yakc_12
	ALIGN	2
YKDelayTask:
	; >>>>> Line:	80
	; >>>>> void YKDelayTask(unsigned count){ 
	jmp	L_yakc_17
L_yakc_18:
	; >>>>> Line:	81
	; >>>>> current_task->tickNum = YKTickNum +count; 
	mov	ax, word [YKTickNum]
	add	ax, word [bp+4]
	mov	si, word [current_task]
	add	si, 36
	mov	word [si], ax
	; >>>>> Line:	82
	; >>>>> ask_to_execu 
	mov	si, word [current_task]
	add	si, 32
	mov	word [si], 0
	; >>>>> Line:	83
	; >>>>> YKScheduler(); 
	call	YKScheduler
	mov	sp, bp
	pop	bp
	ret
L_yakc_17:
	push	bp
	mov	bp, sp
	jmp	L_yakc_18
	ALIGN	2
YKEnterMutex:
	; >>>>> Line:	86
	; >>>>> int YKEnterMutex(){ 
	jmp	L_yakc_20
L_yakc_21:
	; >>>>> Line:	88
	; >>>>> asm("pushf"); 
	pushf
	; >>>>> Line:	89
	; >>>>> asm("pop word [bp-2]"); 
	pop word [bp-2]
	; >>>>> Line:	90
	; >>>>> asm("cli"); 
	cli
	; >>>>> Line:	91
	; >>>>> ireg = ireg & (1 << 9); 
	mov	ax, word [bp-2]
	and	ax, 512
	mov	word [bp-2], ax
	; >>>>> Line:	92
	; >>>>> return ireg; 
	mov	ax, word [bp-2]
L_yakc_22:
	mov	sp, bp
	pop	bp
	ret
L_yakc_20:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_21
	ALIGN	2
YKExitMutex:
	; >>>>> Line:	94
	; >>>>> void YKExitMutex(){ 
	jmp	L_yakc_24
L_yakc_25:
	; >>>>> Line:	95
	; >>>>> asm("sti"); 
	sti
	mov	sp, bp
	pop	bp
	ret
L_yakc_24:
	push	bp
	mov	bp, sp
	jmp	L_yakc_25
	ALIGN	2
YKEnterISR:
	; >>>>> Line:	97
	; >>>>> void YKEnterISR(){ 
	jmp	L_yakc_27
L_yakc_28:
	; >>>>> Line:	98
	; >>>>> if (!isrdepth){ 
	mov	ax, word [isrdepth]
	test	ax, ax
	jne	L_yakc_29
	; >>>>> Line:	99
	; >>>>> saveContext(&current_task->context); 
	mov	ax, word [current_task]
	add	ax, 2
	push	ax
	call	saveContext
	add	sp, 2
L_yakc_29:
	; >>>>> Line:	101
	; >>>>> isrdepth++; 
	inc	word [isrdepth]
	mov	sp, bp
	pop	bp
	ret
L_yakc_27:
	push	bp
	mov	bp, sp
	jmp	L_yakc_28
	ALIGN	2
YKExitISR:
	; >>>>> Line:	103
	; >>>>> void YKExitISR(){ 
	jmp	L_yakc_31
L_yakc_32:
	; >>>>> Line:	104
	; >>>>> isrdepth--; 
	dec	word [isrdepth]
	; >>>>> Line:	105
	; >>>>> if (!isrdepth){ 
	mov	ax, word [isrdepth]
	test	ax, ax
	jne	L_yakc_33
	; >>>>> Line:	106
	; >>>>> YKScheduler(); 
	call	YKScheduler
L_yakc_33:
	mov	sp, bp
	pop	bp
	ret
L_yakc_31:
	push	bp
	mov	bp, sp
	jmp	L_yakc_32
	ALIGN	2
YKScheduler:
	; >>>>> Line:	109
	; >>>>> void YKScheduler() { 
	jmp	L_yakc_35
L_yakc_36:
	; >>>>> Line:	113
	; >>>>> ireg = YKEnterMutex(); 
	call	YKEnterMutex
	mov	word [bp-6], ax
	; >>>>> Line:	114
	; >>>>> for(i=0;i<5;i++) { 
	mov	word [bp-2], 0
	jmp	L_yakc_38
L_yakc_37:
	; >>>>> Line:	115
	; >>>>> if(tasks[i].state == 1) { 
	mov	ax, word [bp-2]
	mov	cx, 42
	imul	cx
	add	ax, tasks
	mov	si, ax
	add	si, 32
	cmp	word [si], 1
	jne	L_yakc_41
	; >>>>> Line:	116
	; >>>>> _execute->context.bp; 
	mov	ax, word [bp-2]
	mov	cx, 42
	imul	cx
	add	ax, tasks
	mov	word [bp-4], ax
	; >>>>> Line:	117
	; >>>>> break; 
	jmp	L_yakc_39
L_yakc_41:
L_yakc_40:
	inc	word [bp-2]
L_yakc_38:
	cmp	word [bp-2], 5
	jl	L_yakc_37
L_yakc_39:
	; >>>>> Line:	120
	; >>>>> if(task_to_execute != current_task) { 
	mov	ax, word [current_task]
	cmp	ax, word [bp-4]
	je	L_yakc_42
	; >>>>> Line:	121
	; >>>>> YKCtxSwCount++; 
	inc	word [YKCtxSwCount]
	; >>>>> Line:	122
	; >>>>> YKDispatcher(task_to_execute); 
	push	word [bp-4]
	call	YKDispatcher
	add	sp, 2
L_yakc_42:
	; >>>>> Line:	125
	; >>>>> if(ireg) 
	mov	ax, word [bp-6]
	test	ax, ax
	je	L_yakc_43
	; >>>>> Line:	126
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
L_yakc_43:
	mov	sp, bp
	pop	bp
	ret
L_yakc_35:
	push	bp
	mov	bp, sp
	sub	sp, 6
	jmp	L_yakc_36
	ALIGN	2
YKDispatcher:
	; >>>>> Line:	128
	; >>>>> void YKDispatcher(TCB * task_to_execute) { 
	jmp	L_yakc_45
L_yakc_46:
	; >>>>> Line:	131
	; >>>>> if(current_task){ 
	mov	ax, word [current_task]
	test	ax, ax
	je	L_yakc_47
	; >>>>> Line:	132
	; >>>>> saveContext(&(current_task->context)); 
	mov	ax, word [current_task]
	add	ax, 2
	push	ax
	call	saveContext
	add	sp, 2
	; >>>>> Line:	133
	; >>>>> Dummy(); 
	call	Dummy
	; >>>>> Line:	134
	; >>>>> if (YKTickNum != current_task->context.tstamp) 
	mov	si, word [current_task]
	add	si, 30
	mov	ax, word [YKTickNum]
	cmp	ax, word [si]
	je	L_yakc_48
	; >>>>> Line:	135
	; >>>>> return; 
	jmp	L_yakc_49
L_yakc_48:
L_yakc_47:
	; >>>>> Line:	137
	; >>>>> current_task = task_to_execute; 
	mov	ax, word [bp+4]
	mov	word [current_task], ax
	; >>>>> Line:	138
	; >>>>> if(task_to_execute->first_time) { 
	mov	si, word [bp+4]
	add	si, 34
	mov	ax, word [si]
	test	ax, ax
	je	L_yakc_50
	; >>>>> Line:	139
	; >>>>> task_to_execute->first_time = 0; 
	mov	si, word [bp+4]
	add	si, 34
	mov	word [si], 0
	; >>>>> Line:	140
	; >>>>> tempreg = task_to_execute->context.bp; 
	mov	si, word [bp+4]
	add	si, 14
	mov	ax, word [si]
	mov	word [bp-2], ax
	; >>>>> Line:	141
	; >>>>> tempreg2 = task_to_execute->task; 
	mov	si, word [bp+4]
	add	si, 40
	mov	ax, word [si]
	mov	word [bp-4], ax
	; >>>>> Line:	142
	; >>>>> Dummy(); 
	call	Dummy
	; >>>>> Line:	143
	; >>>>> asm("mov sp,word [bp-2]"); 
	mov sp,word [bp-2]
	; >>>>> Line:	144
	; >>>>> asm("mov si,word [bp-4]"); 
	mov si,word [bp-4]
	; >>>>> Line:	145
	; >>>>> asm("mov bp,word [bp-2]"); 
	mov bp,word [bp-2]
	; >>>>> Line:	146
	; >>>>> asm("sti"); 
	sti
	; >>>>> Line:	147
	; >>>>> asm("call si"); 
	call si
	; >>>>> Line:	148
	; >>>>> Dummy(); 
	call	Dummy
	jmp	L_yakc_51
L_yakc_50:
	; >>>>> Line:	152
	; >>>>> restoreContext(&(task_to_execute->context)); 
	mov	ax, word [bp+4]
	add	ax, 2
	push	ax
	call	restoreContext
	add	sp, 2
L_yakc_51:
L_yakc_49:
	; >>>>> Line:	154
	; >>>>> return; 
	mov	sp, bp
	pop	bp
	ret
L_yakc_45:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_yakc_46
	ALIGN	2
saveContext:
	; >>>>> Line:	157
	; >>>>> void saveContext(Context * context) { 
	jmp	L_yakc_53
L_yakc_54:
	; >>>>> Line:	161
	; >>>>> context->tstamp = YKTickNum; 
	mov	word [bp-2], 3
	; >>>>> Line:	161
	; >>>>> context->tstamp = YKTickNum; 
	mov	si, word [bp+4]
	add	si, 28
	mov	ax, word [YKTickNum]
	mov	word [si], ax
	; >>>>> Line:	163
	; >>>>> asm("mov word [bp-2], ax"); 
	mov word [bp-2], ax
	; >>>>> Line:	164
	; >>>>> context->ax = tempreg; 
	mov	si, word [bp+4]
	mov	ax, word [bp-2]
	mov	word [si], ax
	; >>>>> Line:	166
	; >>>>> asm("pushf"); 
	pushf
	; >>>>> Line:	167
	; >>>>> asm("pop ax"); 
	pop ax
	; >>>>> Line:	169
	; >>>>> asm("mov word [bp-2], ax"); 
	mov word [bp-2], ax
	; >>>>> Line:	170
	; >>>>> context->flags = tempreg; 
	mov	si, word [bp+4]
	add	si, 26
	mov	ax, word [bp-2]
	mov	word [si], ax
	; >>>>> Line:	172
	; >>>>> asm("mov word [bp-2], bx"); 
	mov word [bp-2], bx
	; >>>>> Line:	173
	; >>>>> context->bx = tempreg; 
	mov	si, word [bp+4]
	add	si, 2
	mov	ax, word [bp-2]
	mov	word [si], ax
	; >>>>> Line:	174
	; >>>>> asm("mov word [bp-2], cx"); 
	mov word [bp-2], cx
	; >>>>> Line:	175
	; >>>>> context->cx = tempreg; 
	mov	si, word [bp+4]
	add	si, 4
	mov	ax, word [bp-2]
	mov	word [si], ax
	; >>>>> Line:	176
	; >>>>> asm("mov word [bp-2], dx"); 
	mov word [bp-2], dx
	; >>>>> Line:	177
	; >>>>> context->dx = tempreg; 
	mov	si, word [bp+4]
	add	si, 6
	mov	ax, word [bp-2]
	mov	word [si], ax
	; >>>>> Line:	179
	; >>>>> asm("mov word ax, word [bp+2]"); 
	mov word ax, word [bp+2]
	; >>>>> Line:	180
	; >>>>> asm("mov word [bp-2], ax"); 
	mov word [bp-2], ax
	; >>>>> Line:	181
	; >>>>> context->ip = tempreg; 
	mov	si, word [bp+4]
	add	si, 8
	mov	ax, word [bp-2]
	mov	word [si], ax
	; >>>>> Line:	182
	; >>>>> asm("mov word [bp-2], sp"); 
	mov word [bp-2], sp
	; >>>>> Line:	183
	; >>>>> context->sp = tempreg; 
	mov	si, word [bp+4]
	add	si, 10
	mov	ax, word [bp-2]
	mov	word [si], ax
	; >>>>> Line:	186
	; >>>>> asm("mov word [bp-2], si"); 
	mov word [bp-2], si
	; >>>>> Line:	187
	; >>>>> context->si = tempreg; 
	mov	si, word [bp+4]
	add	si, 14
	mov	ax, word [bp-2]
	mov	word [si], ax
	; >>>>> Line:	188
	; >>>>> asm("mov word [bp-2], di"); 
	mov word [bp-2], di
	; >>>>> Line:	189
	; >>>>> context->di = tempreg; 
	mov	si, word [bp+4]
	add	si, 16
	mov	ax, word [bp-2]
	mov	word [si], ax
	; >>>>> Line:	191
	; >>>>> asm("mov word [bp-2], cs"); 
	mov word [bp-2], cs
	; >>>>> Line:	192
	; >>>>> context->cs = tempreg; 
	mov	si, word [bp+4]
	add	si, 18
	mov	ax, word [bp-2]
	mov	word [si], ax
	; >>>>> Line:	193
	; >>>>> asm("mov word [bp-2], ds"); 
	mov word [bp-2], ds
	; >>>>> Line:	194
	; >>>>> context->ds = tempreg; 
	mov	si, word [bp+4]
	add	si, 20
	mov	ax, word [bp-2]
	mov	word [si], ax
	; >>>>> Line:	195
	; >>>>> asm("mov word [bp-2], ss" 
	mov word [bp-2], ss
	; >>>>> Line:	196
	; >>>>> context->ss = tempreg; 
	mov	si, word [bp+4]
	add	si, 22
	mov	ax, word [bp-2]
	mov	word [si], ax
	; >>>>> Line:	197
	; >>>>> asm("mov word [bp-2], es"); 
	mov word [bp-2], es
	; >>>>> Line:	198
	; >>>>> context->es = tempreg; 
	mov	si, word [bp+4]
	add	si, 24
	mov	ax, word [bp-2]
	mov	word [si], ax
	; >>>>> Line:	199
	; >>>>> asm("push word [bp]"); 
	push word [bp]
	; >>>>> Line:	200
	; >>>>> asm("pop word [bp-2]"); 
	pop word [bp-2]
	; >>>>> Line:	201
	; >>>>> context->bp = tempreg; 
	mov	si, word [bp+4]
	add	si, 12
	mov	ax, word [bp-2]
	mov	word [si], ax
	mov	sp, bp
	pop	bp
	ret
L_yakc_53:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_54
	ALIGN	2
restoreContext:
	; >>>>> Line:	206
	; >>>>> void restoreContext(Context * context) { 
	jmp	L_yakc_56
L_yakc_57:
	; >>>>> Line:	211
	; >>>>> tempreg = context->bx ; 
	mov	si, word [bp+4]
	add	si, 2
	mov	ax, word [si]
	mov	word [bp-2], ax
	; >>>>> Line:	212
	; >>>>> asm("mov word bx, [bp-2]"); 
	mov word bx, [bp-2]
	; >>>>> Line:	213
	; >>>>> tempreg = context->cx ; 
	mov	si, word [bp+4]
	add	si, 4
	mov	ax, word [si]
	mov	word [bp-2], ax
	; >>>>> Line:	214
	; >>>>> asm("mov word cx, [bp-2]"); 
	mov word cx, [bp-2]
	; >>>>> Line:	215
	; >>>>> tempreg = context->dx ; 
	mov	si, word [bp+4]
	add	si, 6
	mov	ax, word [si]
	mov	word [bp-2], ax
	; >>>>> Line:	216
	; >>>>> asm("mov word dx, [bp-2]"); 
	mov word dx, [bp-2]
	; >>>>> Line:	218
	; >>>>> tempreg = context->bp ; 
	mov	si, word [bp+4]
	add	si, 12
	mov	ax, word [si]
	mov	word [bp-2], ax
	; >>>>> Line:	219
	; >>>>> asm("mov word sp, [bp-2]"); 
	mov word sp, [bp-2]
	; >>>>> Line:	220
	; >>>>> tempreg = context->si ; 
	mov	si, word [bp+4]
	add	si, 14
	mov	ax, word [si]
	mov	word [bp-2], ax
	; >>>>> Line:	221
	; >>>>> asm("mov word si, [bp-2]"); 
	mov word si, [bp-2]
	; >>>>> Line:	222
	; >>>>> tempreg = context->di ; 
	mov	si, word [bp+4]
	add	si, 16
	mov	ax, word [si]
	mov	word [bp-2], ax
	; >>>>> Line:	223
	; >>>>> asm("mov word di, [bp-2]"); 
	mov word di, [bp-2]
	; >>>>> Line:	225
	; >>>>> tempreg = context->cs ; 
	mov	si, word [bp+4]
	add	si, 18
	mov	ax, word [si]
	mov	word [bp-2], ax
	; >>>>> Line:	226
	; >>>>> asm("mov word cs, [bp-2]"); 
	mov word cs, [bp-2]
	; >>>>> Line:	227
	; >>>>> tempreg = context->ds ; 
	mov	si, word [bp+4]
	add	si, 20
	mov	ax, word [si]
	mov	word [bp-2], ax
	; >>>>> Line:	228
	; >>>>> asm("mov word ds, [bp-2]"); 
	mov word ds, [bp-2]
	; >>>>> Line:	229
	; >>>>> tempreg = context->ss ; 
	mov	si, word [bp+4]
	add	si, 22
	mov	ax, word [si]
	mov	word [bp-2], ax
	; >>>>> Line:	230
	; >>>>> asm("mov word ss, [bp-2]"); 
	mov word ss, [bp-2]
	; >>>>> Line:	231
	; >>>>> tempreg = context->es ; 
	mov	si, word [bp+4]
	add	si, 24
	mov	ax, word [si]
	mov	word [bp-2], ax
	; >>>>> Line:	232
	; >>>>> asm("mov word es, [bp-2]"); 
	mov word es, [bp-2]
	; >>>>> Line:	237
	; >>>>> tempreg = context->flags; 
	mov	si, word [bp+4]
	add	si, 26
	mov	ax, word [si]
	mov	word [bp-2], ax
	; >>>>> Line:	238
	; >>>>> asm("push word [bp-2]"); 
	push word [bp-2]
	; >>>>> Line:	240
	; >>>>> tempreg = context->ax; 
	mov	si, word [bp+4]
	mov	ax, word [si]
	mov	word [bp-2], ax
	; >>>>> Line:	241
	; >>>>> asm("push word [bp-2]"); 
	push word [bp-2]
	; >>>>> Line:	242
	; >>>>> tempreg = context->si; 
	mov	si, word [bp+4]
	add	si, 14
	mov	ax, word [si]
	mov	word [bp-2], ax
	; >>>>> Line:	243
	; >>>>> asm("push word [bp-2]"); 
	push word [bp-2]
	; >>>>> Line:	245
	; >>>>> asm("pop si"); 
	pop si
	; >>>>> Line:	246
	; >>>>> asm("pop ax"); 
	pop ax
	; >>>>> Line:	247
	; >>>>> asm("popf"); 
	popf
	; >>>>> Line:	248
	; >>>>> asm("pop bp"); 
	pop bp
L_yakc_58:
	; >>>>> Line:	250
	; >>>>> return; 
	mov	sp, bp
	pop	bp
	ret
L_yakc_56:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_57
L_yakc_60:
	DB	"TICK ",0
	ALIGN	2
YKTickHandler:
	; >>>>> Line:	253
	; >>>>> void YKTickHandler() { 
	jmp	L_yakc_61
L_yakc_62:
	; >>>>> Line:	255
	; >>>>>  
	call	printNewLine
	; >>>>> Line:	256
	; >>>>> printString("TICK "); 
	mov	ax, L_yakc_60
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	257
	; >>>>> printUInt(++YKTickNum); 
	mov	ax, word [YKTickNum]
	inc	ax
	mov	word [YKTickNum], ax
	push	ax
	call	printUInt
	add	sp, 2
	; >>>>> Line:	258
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	259
	; >>>>> for(i=0;i<5;i++) { 
	mov	word [bp-2], 0
	jmp	L_yakc_64
L_yakc_63:
	; >>>>> Line:	260
	; >>>>> if(tasks[i].tickNum == YKTickNum) { 
	mov	ax, word [bp-2]
	mov	cx, 42
	imul	cx
	add	ax, tasks
	mov	si, ax
	add	si, 36
	mov	ax, word [YKTickNum]
	cmp	ax, word [si]
	jne	L_yakc_67
	; >>>>> Line:	261
	; >>>>> tasks[i].state = 1; 
	mov	ax, word [bp-2]
	mov	cx, 42
	imul	cx
	add	ax, tasks
	mov	si, ax
	add	si, 32
	mov	word [si], 1
L_yakc_67:
L_yakc_66:
	inc	word [bp-2]
L_yakc_64:
	cmp	word [bp-2], 5
	jl	L_yakc_63
L_yakc_65:
	mov	sp, bp
	pop	bp
	ret
L_yakc_61:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_62
	ALIGN	2
YKCtxSwCount:
	TIMES	2 db 0
YKIdleCount:
	TIMES	2 db 0
YKTickNum:
	TIMES	2 db 0
running:
	TIMES	2 db 0
current_task:
	TIMES	2 db 0
id_counter:
	TIMES	2 db 0
tasks:
	TIMES	4200 db 0
IdleStk:
	TIMES	512 db 0
isrdepth:
	TIMES	2 db 0
NumTasks:
	TIMES	2 db 0
